### ISSUE TITLE
Double-sided Matrix cards

### ISSUE THREAD

**Issue by garykac** [garykac/blockchain#11]
One of the motivations for have multiple Matrix cards visible is that is can be frustrating when a player wants a symbol that it not available. The approach of having multiple Matrix cards visible increases the likelihood that a card with the desired is available.

Since the top Matrix card is always visible and the player never needs to hide a Matrix card from other players, there is no need for a common back pattern on the card. So:

* The Matrix cards could be double-sided
* The elements on front and back can be balanced so that each element occurs once (and only once) on a card.
   * So if a symbol is not shown on the top Matrix card, it is guaranteed to be on the other side.
* When a player chooses a card they can choose to meld either side into their matrix.

Pros:
* There can be a single stack of Matrix cards with a single card visible (and every element is still available for the player). No need to maintain a set of available cards.
* The player can set their initial starting Matrix card to either side. So if a player wants to start with a particular element, they are guaranteed to be able to.

Cons:
* The downside when choosing the hidden side is that the player doesn't know the exact layout of the back of the card when choosing the card.
* Player can learn the pattern relationship between the front and back and know which back corresponds to a particular front. This would possibly give a slight advantage.

**Comment by garykac** [comment]
The pattern between front and back can be made (mostly) obvious:

## 4

With Air / Earth and Fire / Water opposite each other on front/back.

```
+-------+           +-------+
| X X X |   <--->   | X X X |
| X     |           |     X |
+-------+           +-------+
```

```
+-------+           +-------+
|   X X |   <--->   | X X   |
| X X   |           |   X X |
+-------+           +-------+
```

```
+-------+           +-------+
| X   X |   <--->   | X   X |
| X X   |           |   X X |
+-------+           +-------+
```

```
+-------+           +-------+
|   X   |   <--->   |   X   |
| X X X |           | X X X |
+-------+           +-------+
```

## 3 <-> 5

```
+-------+           +-------+
|   X X |   <--->   | X X X |
| X     |           |   X X |
+-------+           +-------+
```

```
+-------+           +-------+
| X     |   <--->   |   X X |
|   X X |           | X X X |
+-------+           +-------+
```

```
+-------+           +-------+
|   X   |   <--->   | X   X |
| X   X |           | X X X |
+-------+           +-------+
```

**Comment by garykac** [comment]
Since the 3-block and 5-block cards have each other on the back (and similarly with some 4-block cards), overall card count could be reduced from 66 to 33.

Single sided:
* 3-block
   * 12 = 3 patterns x 4 element combos
* 4-block
   * 42 = 7 patterns x 6 element combos
* 5-block
   * 12 = 3 patterns x 4 element combos
* Total = 66

Double-sided (with dups removed)
* 3- and 5-block
   * 12 = 3 patterns x 4 element combos
* 4-block
   * 21 = 3 patterns x 6 element combos + 1 pattern x 3 element combos
* Total = 33

**Comment by garykac** [comment]
This also enables another potential player interaction, where a special attack can force a player to flip over one of their Matrix cards to the other side. Since there are 2 ways to flip over a card, the targeted player gets to choose.

**Comment by blinks** [comment]
I still feel like your matrix should be sacred, but could be convinced.
